on: push

jobs:

  windows-tests:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: coursier-setup-action
        uses: coursier/setup-action@v1.3.0
      - name: Create env file
        shell: bash
        run: |
          echo "export GITHUB_TOKEN=${{ secrets.TOKEN }}" >> .env
      - name: Run steps
        shell: bash
        run: |
          echo "Installing CARGO"
          curl https://sh.rustup.rs -sSf | sh -s -- -y 
          echo "Cargo Installed"

          echo "Installing ARGC"
          cargo install argc
          echo "ARGC Installed"

          echo "Installing Giter"
          cs install giter8
          echo "Gitter Installed"
      - name: Run Hydra
        shell: bash
        run: |
          giter8 t
          scripts/hydra install

          scripts/hydra build

          scripts/hydra start_genesis

          scripts/hydra stop

          scripts/hydra destroy