on: push

jobs:

  windows-tests:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Setup WSL
        uses: Vampire/setup-wsl@v2
        with:
          additional-packages: curl
          distribution: Ubuntu-20.04
      - name: Run Steps
        shell: wsl-bash_Ubuntu-20.04 {0}
        run: |
          echo "export GITHUB_TOKEN=${{ secrets.TOKEN }}" >> .env
          sudo apt-get update -y
          sudo apt install build-essential -y
          echo "Installing CARGO"
          curl https://sh.rustup.rs -sSf | sh -s -- -y 
          echo "Cargo Installed"

          source "$HOME/.cargo/env"
  
          echo "Installing ARGC"
          cargo install argc
          echo "ARGC Installed"
 
          echo "Installing Scala"
          curl -fL https://github.com/coursier/coursier/releases/download/v2.1.0/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup -y
          echo "Scala Installed"
          
          echo "Installing Giter"
          cs install giter8
          echo "Gitter Installed"
          
          source ~/.profile
 
          scripts/hydra install
 
          scripts/hydra build
 
          scripts/hydra start_genesis
 
          scripts/hydra stop
 
          scripts/hydra destroy